// IT IS GENERATED BY FLR - DO NOT MODIFY BY HAND
// YOU CAN GET MORE DETAILS ABOUT FLR FROM:
// - https://github.com/Fly-Mix/flr-cli
// - https://github.com/Fly-Mix/flr-vscode-extension
// - https://github.com/Fly-Mix/flr-as-plugin
//

// ignore: unused_import
import 'package:flutter/services.dart' show rootBundle;
// ignore: unused_import
import 'package:flutter/widgets.dart';
// ignore: unused_import
import 'package:flutter_svg/flutter_svg.dart';
// ignore: unused_import
import 'package:path/path.dart' as path;
// ignore: unused_import
import 'package:r_dart_library/asset_svg.dart';

/// This `R` class is generated and contains references to static asset resources.
class R {
  /// package name: six
  static const package = "six";

  /// This `R.image` struct is generated, and contains static references to static non-svg type image asset resources.
  static const image = _R_Image();

  /// This `R.svg` struct is generated, and contains static references to static svg type image asset resources.
  static const svg = _R_Svg();

  /// This `R.text` struct is generated, and contains static references to static text asset resources.
  static const text = _R_Text();

  /// This `R.fontFamily` struct is generated, and contains static references to static font asset resources.
  static const fontFamily = _R_FontFamily();
}

/// Asset resource’s metadata class.
/// For example, here is the metadata of `packages/flutter_demo/assets/images/example.png` asset:
/// - packageName：flutter_demo
/// - assetName：assets/images/example.png
/// - fileDirname：assets/images
/// - fileBasename：example.png
/// - fileBasenameNoExtension：example
/// - fileExtname：.png
class AssetResource {
  /// Creates an object to hold the asset resource’s metadata.
  const AssetResource(this.assetName, {this.packageName});

  /// The name of the main asset from the set of asset resources to choose from.
  final String assetName;

  /// The name of the package from which the asset resource is included.
  final String? packageName;

  /// The name used to generate the key to obtain the asset resource. For local assets
  /// this is [assetName], and for assets from packages the [assetName] is
  /// prefixed 'packages/<package_name>/'.
  String get keyName =>
      packageName == null ? assetName : "packages/$packageName/$assetName";

  /// The file basename of the asset resource.
  String get fileBasename {
    final basename = path.basename(assetName);
    return basename;
  }

  /// The no extension file basename of the asset resource.
  String get fileBasenameNoExtension {
    final basenameWithoutExtension = path.basenameWithoutExtension(assetName);
    return basenameWithoutExtension;
  }

  /// The file extension name of the asset resource.
  String get fileExtname {
    final extension = path.extension(assetName);
    return extension;
  }

  /// The directory path name of the asset resource.
  String get fileDirname {
    var dirname = assetName;
    if (packageName != null) {
      final packageStr = "packages/$packageName/";
      dirname = dirname.replaceAll(packageStr, "");
    }
    final filenameStr = "$fileBasename/";
    dirname = dirname.replaceAll(filenameStr, "");
    return dirname;
  }
}

// ignore: camel_case_types
class _R_Image_AssetResource {
  const _R_Image_AssetResource();

  /// asset: assets/images/Calendar.png
  // ignore: non_constant_identifier_names
  final calendar =
      const AssetResource("assets/images/Calendar.png", packageName: null);

  /// asset: assets/images/Discount.png
  // ignore: non_constant_identifier_names
  final discount =
      const AssetResource("assets/images/Discount.png", packageName: null);

  /// asset: assets/images/Home.png
  // ignore: non_constant_identifier_names
  final home = const AssetResource("assets/images/Home.png", packageName: null);

  /// asset: assets/images/Home_active.png
  // ignore: non_constant_identifier_names
  final home_active =
      const AssetResource("assets/images/Home_active.png", packageName: null);

  /// asset: assets/images/Profile.png
  // ignore: non_constant_identifier_names
  final profile =
      const AssetResource("assets/images/Profile.png", packageName: null);

  /// asset: assets/images/Profile_active.png
  // ignore: non_constant_identifier_names
  final profile_active = const AssetResource("assets/images/Profile_active.png",
      packageName: null);

  /// asset: assets/images/bell.png
  // ignore: non_constant_identifier_names
  final bell = const AssetResource("assets/images/bell.png", packageName: null);

  /// asset: assets/images/charity_ticket.png
  // ignore: non_constant_identifier_names
  final charity_ticket = const AssetResource("assets/images/charity_ticket.png",
      packageName: null);

  /// asset: assets/images/charity_ticket_select.png
  // ignore: non_constant_identifier_names
  final charity_ticket_select = const AssetResource(
      "assets/images/charity_ticket_select.png",
      packageName: null);

  /// asset: assets/images/discoun_active.png
  // ignore: non_constant_identifier_names
  final discoun_active = const AssetResource("assets/images/discoun_active.png",
      packageName: null);

  /// asset: assets/images/email.png
  // ignore: non_constant_identifier_names
  final email =
      const AssetResource("assets/images/email.png", packageName: null);

  /// asset: assets/images/error_dialog.png
  // ignore: non_constant_identifier_names
  final error_dialog =
      const AssetResource("assets/images/error_dialog.png", packageName: null);

  /// asset: assets/images/feedback.png
  // ignore: non_constant_identifier_names
  final feedback =
      const AssetResource("assets/images/feedback.png", packageName: null);

  /// asset: assets/images/food.png
  // ignore: non_constant_identifier_names
  final food = const AssetResource("assets/images/food.png", packageName: null);

  /// asset: assets/images/home_new.png
  // ignore: non_constant_identifier_names
  final home_new =
      const AssetResource("assets/images/home_new.png", packageName: null);

  /// asset: assets/images/image_picker.png
  // ignore: non_constant_identifier_names
  final image_picker =
      const AssetResource("assets/images/image_picker.png", packageName: null);

  /// asset: assets/images/man.png
  // ignore: non_constant_identifier_names
  final man = const AssetResource("assets/images/man.png", packageName: null);

  /// asset: assets/images/onb_1.png
  // ignore: non_constant_identifier_names
  final onb_1 =
      const AssetResource("assets/images/onb_1.png", packageName: null);

  /// asset: assets/images/onb_2.png
  // ignore: non_constant_identifier_names
  final onb_2 =
      const AssetResource("assets/images/onb_2.png", packageName: null);

  /// asset: assets/images/onb_3.png
  // ignore: non_constant_identifier_names
  final onb_3 =
      const AssetResource("assets/images/onb_3.png", packageName: null);

  /// asset: assets/images/onboarding_5.png
  // ignore: non_constant_identifier_names
  final onboarding_5 =
      const AssetResource("assets/images/onboarding_5.png", packageName: null);

  /// asset: assets/images/onboarding_6.png
  // ignore: non_constant_identifier_names
  final onboarding_6 =
      const AssetResource("assets/images/onboarding_6.png", packageName: null);

  /// asset: assets/images/onboarding_7.png
  // ignore: non_constant_identifier_names
  final onboarding_7 =
      const AssetResource("assets/images/onboarding_7.png", packageName: null);

  /// asset: assets/images/phone.png
  // ignore: non_constant_identifier_names
  final phone =
      const AssetResource("assets/images/phone.png", packageName: null);

  /// asset: assets/images/privacy.png
  // ignore: non_constant_identifier_names
  final privacy =
      const AssetResource("assets/images/privacy.png", packageName: null);

  /// asset: assets/images/profile_new.png
  // ignore: non_constant_identifier_names
  final profile_new =
      const AssetResource("assets/images/profile_new.png", packageName: null);

  /// asset: assets/images/qr_border.png
  // ignore: non_constant_identifier_names
  final qr_border =
      const AssetResource("assets/images/qr_border.png", packageName: null);

  /// asset: assets/images/request.png
  // ignore: non_constant_identifier_names
  final request =
      const AssetResource("assets/images/request.png", packageName: null);

  /// asset: assets/images/select_voucher.png
  // ignore: non_constant_identifier_names
  final select_voucher = const AssetResource("assets/images/select_voucher.png",
      packageName: null);

  /// asset: assets/images/six_logo.png
  // ignore: non_constant_identifier_names
  final six_logo =
      const AssetResource("assets/images/six_logo.png", packageName: null);

  /// asset: assets/images/success_redem.png
  // ignore: non_constant_identifier_names
  final success_redem =
      const AssetResource("assets/images/success_redem.png", packageName: null);

  /// asset: assets/images/super_market.png
  // ignore: non_constant_identifier_names
  final super_market =
      const AssetResource("assets/images/super_market.png", packageName: null);

  /// asset: assets/images/support.png
  // ignore: non_constant_identifier_names
  final support =
      const AssetResource("assets/images/support.png", packageName: null);

  /// asset: assets/images/term_c.png
  // ignore: non_constant_identifier_names
  final term_c =
      const AssetResource("assets/images/term_c.png", packageName: null);

  /// asset: assets/images/ticket.png
  // ignore: non_constant_identifier_names
  final ticket =
      const AssetResource("assets/images/ticket.png", packageName: null);

  /// asset: assets/images/ticket_click.png
  // ignore: non_constant_identifier_names
  final ticket_click =
      const AssetResource("assets/images/ticket_click.png", packageName: null);

  /// asset: assets/images/transport.png
  // ignore: non_constant_identifier_names
  final transport =
      const AssetResource("assets/images/transport.png", packageName: null);

  /// asset: assets/images/vendor_onb1.png
  // ignore: non_constant_identifier_names
  final vendor_onb1 =
      const AssetResource("assets/images/vendor_onb1.png", packageName: null);

  /// asset: assets/images/vendor_onb2.png
  // ignore: non_constant_identifier_names
  final vendor_onb2 =
      const AssetResource("assets/images/vendor_onb2.png", packageName: null);

  /// asset: assets/images/voucher_card_1.png
  // ignore: non_constant_identifier_names
  final voucher_card_1 = const AssetResource("assets/images/voucher_card_1.png",
      packageName: null);

  /// asset: assets/images/voucher_filter.png
  // ignore: non_constant_identifier_names
  final voucher_filter = const AssetResource("assets/images/voucher_filter.png",
      packageName: null);
}

// ignore: camel_case_types
class _R_Svg_AssetResource {
  const _R_Svg_AssetResource();
}

// ignore: camel_case_types
class _R_Text_AssetResource {
  const _R_Text_AssetResource();
}

/// This `_R_Image` class is generated and contains references to static non-svg type image asset resources.
// ignore: camel_case_types
class _R_Image {
  const _R_Image();

  final asset = const _R_Image_AssetResource();

  /// asset: assets/images/Calendar.png
  // ignore: non_constant_identifier_names
  AssetImage calendar() {
    return AssetImage(asset.calendar.keyName);
  }

  /// asset: assets/images/Discount.png
  // ignore: non_constant_identifier_names
  AssetImage discount() {
    return AssetImage(asset.discount.keyName);
  }

  /// asset: assets/images/Home.png
  // ignore: non_constant_identifier_names
  AssetImage home() {
    return AssetImage(asset.home.keyName);
  }

  /// asset: assets/images/Home_active.png
  // ignore: non_constant_identifier_names
  AssetImage home_active() {
    return AssetImage(asset.home_active.keyName);
  }

  /// asset: assets/images/Profile.png
  // ignore: non_constant_identifier_names
  AssetImage profile() {
    return AssetImage(asset.profile.keyName);
  }

  /// asset: assets/images/Profile_active.png
  // ignore: non_constant_identifier_names
  AssetImage profile_active() {
    return AssetImage(asset.profile_active.keyName);
  }

  /// asset: assets/images/bell.png
  // ignore: non_constant_identifier_names
  AssetImage bell() {
    return AssetImage(asset.bell.keyName);
  }

  /// asset: assets/images/charity_ticket.png
  // ignore: non_constant_identifier_names
  AssetImage charity_ticket() {
    return AssetImage(asset.charity_ticket.keyName);
  }

  /// asset: assets/images/charity_ticket_select.png
  // ignore: non_constant_identifier_names
  AssetImage charity_ticket_select() {
    return AssetImage(asset.charity_ticket_select.keyName);
  }

  /// asset: assets/images/discoun_active.png
  // ignore: non_constant_identifier_names
  AssetImage discoun_active() {
    return AssetImage(asset.discoun_active.keyName);
  }

  /// asset: assets/images/email.png
  // ignore: non_constant_identifier_names
  AssetImage email() {
    return AssetImage(asset.email.keyName);
  }

  /// asset: assets/images/error_dialog.png
  // ignore: non_constant_identifier_names
  AssetImage error_dialog() {
    return AssetImage(asset.error_dialog.keyName);
  }

  /// asset: assets/images/feedback.png
  // ignore: non_constant_identifier_names
  AssetImage feedback() {
    return AssetImage(asset.feedback.keyName);
  }

  /// asset: assets/images/food.png
  // ignore: non_constant_identifier_names
  AssetImage food() {
    return AssetImage(asset.food.keyName);
  }

  /// asset: assets/images/home_new.png
  // ignore: non_constant_identifier_names
  AssetImage home_new() {
    return AssetImage(asset.home_new.keyName);
  }

  /// asset: assets/images/image_picker.png
  // ignore: non_constant_identifier_names
  AssetImage image_picker() {
    return AssetImage(asset.image_picker.keyName);
  }

  /// asset: assets/images/man.png
  // ignore: non_constant_identifier_names
  AssetImage man() {
    return AssetImage(asset.man.keyName);
  }

  /// asset: assets/images/onb_1.png
  // ignore: non_constant_identifier_names
  AssetImage onb_1() {
    return AssetImage(asset.onb_1.keyName);
  }

  /// asset: assets/images/onb_2.png
  // ignore: non_constant_identifier_names
  AssetImage onb_2() {
    return AssetImage(asset.onb_2.keyName);
  }

  /// asset: assets/images/onb_3.png
  // ignore: non_constant_identifier_names
  AssetImage onb_3() {
    return AssetImage(asset.onb_3.keyName);
  }

  /// asset: assets/images/onboarding_5.png
  // ignore: non_constant_identifier_names
  AssetImage onboarding_5() {
    return AssetImage(asset.onboarding_5.keyName);
  }

  /// asset: assets/images/onboarding_6.png
  // ignore: non_constant_identifier_names
  AssetImage onboarding_6() {
    return AssetImage(asset.onboarding_6.keyName);
  }

  /// asset: assets/images/onboarding_7.png
  // ignore: non_constant_identifier_names
  AssetImage onboarding_7() {
    return AssetImage(asset.onboarding_7.keyName);
  }

  /// asset: assets/images/phone.png
  // ignore: non_constant_identifier_names
  AssetImage phone() {
    return AssetImage(asset.phone.keyName);
  }

  /// asset: assets/images/privacy.png
  // ignore: non_constant_identifier_names
  AssetImage privacy() {
    return AssetImage(asset.privacy.keyName);
  }

  /// asset: assets/images/profile_new.png
  // ignore: non_constant_identifier_names
  AssetImage profile_new() {
    return AssetImage(asset.profile_new.keyName);
  }

  /// asset: assets/images/qr_border.png
  // ignore: non_constant_identifier_names
  AssetImage qr_border() {
    return AssetImage(asset.qr_border.keyName);
  }

  /// asset: assets/images/request.png
  // ignore: non_constant_identifier_names
  AssetImage request() {
    return AssetImage(asset.request.keyName);
  }

  /// asset: assets/images/select_voucher.png
  // ignore: non_constant_identifier_names
  AssetImage select_voucher() {
    return AssetImage(asset.select_voucher.keyName);
  }

  /// asset: assets/images/six_logo.png
  // ignore: non_constant_identifier_names
  AssetImage six_logo() {
    return AssetImage(asset.six_logo.keyName);
  }

  /// asset: assets/images/success_redem.png
  // ignore: non_constant_identifier_names
  AssetImage success_redem() {
    return AssetImage(asset.success_redem.keyName);
  }

  /// asset: assets/images/super_market.png
  // ignore: non_constant_identifier_names
  AssetImage super_market() {
    return AssetImage(asset.super_market.keyName);
  }

  /// asset: assets/images/support.png
  // ignore: non_constant_identifier_names
  AssetImage support() {
    return AssetImage(asset.support.keyName);
  }

  /// asset: assets/images/term_c.png
  // ignore: non_constant_identifier_names
  AssetImage term_c() {
    return AssetImage(asset.term_c.keyName);
  }

  /// asset: assets/images/ticket.png
  // ignore: non_constant_identifier_names
  AssetImage ticket() {
    return AssetImage(asset.ticket.keyName);
  }

  /// asset: assets/images/ticket_click.png
  // ignore: non_constant_identifier_names
  AssetImage ticket_click() {
    return AssetImage(asset.ticket_click.keyName);
  }

  /// asset: assets/images/transport.png
  // ignore: non_constant_identifier_names
  AssetImage transport() {
    return AssetImage(asset.transport.keyName);
  }

  /// asset: assets/images/vendor_onb1.png
  // ignore: non_constant_identifier_names
  AssetImage vendor_onb1() {
    return AssetImage(asset.vendor_onb1.keyName);
  }

  /// asset: assets/images/vendor_onb2.png
  // ignore: non_constant_identifier_names
  AssetImage vendor_onb2() {
    return AssetImage(asset.vendor_onb2.keyName);
  }

  /// asset: assets/images/voucher_card_1.png
  // ignore: non_constant_identifier_names
  AssetImage voucher_card_1() {
    return AssetImage(asset.voucher_card_1.keyName);
  }

  /// asset: assets/images/voucher_filter.png
  // ignore: non_constant_identifier_names
  AssetImage voucher_filter() {
    return AssetImage(asset.voucher_filter.keyName);
  }
}

/// This `_R_Svg` class is generated and contains references to static svg type image asset resources.
// ignore: camel_case_types
class _R_Svg {
  const _R_Svg();

  final asset = const _R_Svg_AssetResource();
}

/// This `_R_Text` class is generated and contains references to static text asset resources.
// ignore: camel_case_types
class _R_Text {
  const _R_Text();

  final asset = const _R_Text_AssetResource();
}

/// This `_R_FontFamily` class is generated and contains references to static font asset resources.
// ignore: camel_case_types
class _R_FontFamily {
  const _R_FontFamily();
}
